language: ruby
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4.0
  - ruby-head
  - jruby
  - jruby-head
before_install:
  - gem install bundler
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
